"""Public API for the Weldall Python SDK."""

from importlib.metadata import PackageNotFoundError, version

from .constants import (
    DPOP_FUTURE_SKEW_SECONDS,
    DPOP_MAX_AGE_SECONDS,
    ID_JAG_DRAFT,
    ID_JAG_TOKEN_TYPE,
    JWT_DPOP_DRAFT,
    JWT_DPOP_GRANT,
    MACHINE_TOKEN_LIFETIME_SECONDS,
    MACHINE_TOKEN_TYP,
    PRIVATE_KEY_JWT_ASSERTION_TYPE,
    REFRESH_TOKEN_TYPE,
    SKILL_ASSERTION_TYPE,
    SKILL_CATALOG_PATH,
    SKILL_CATALOG_SCHEMA_VERSION,
    SKILL_TAG_LENGTH_LIMIT,
    SKILL_TAG_LIMIT,
    TOKEN_EXCHANGE_GRANT,
)
from .core import Weldall, WeldallHandlers, init_weldall
from .crypto import (
    assert_public_p256,
    base64url_sha256,
    calculate_jwk_thumbprint,
    generate_es256_key_pair,
    is_sha256_jwk_thumbprint,
    public_jwk,
    safe_equal,
    validate_es256_key_pair,
)
from .discovery import WeldallDiscovery
from .dpop import (
    CreateDpopProofInput,
    VerifyStrictDpopInput,
    create_dpop_proof,
    normalize_htu,
    verify_strict_dpop,
)
from .errors import (
    ErrorResponse,
    WeldallAuthError,
    oauth_error_parts,
    oauth_error_response,
)
from .http import Headers, Request, Response
from .id_jag import IssueIdJagInput, VerifyIdJagInput, issue_id_jag, verify_id_jag
from .identity import has_verified_email
from .jwt import (
    JwtSigningInput,
    JwtVerificationInput,
    decode_jwt,
    decode_protected_header,
    load_es256_key_pair_from_env,
    parse_jwk_env,
    sign_es256,
    verify_es256,
)
from .machine import (
    MachineClientAssertionInput,
    MachineKey,
    MachineToken,
    MachineTokenRequestInput,
    create_machine_client_assertion,
    request_machine_token,
)
from .replay import InMemoryReplayStore, consume_replay, in_memory
from .resource_as import (
    IssueAccessTokenInput,
    VerifyAccessTokenInput,
    issue_access_token,
    verify_access_token,
)
from .resource_registry import (
    normalize_authorization_server,
    normalize_request_prefix,
    normalize_request_target,
    normalize_resource_identifier,
    request_prefix_accepts,
    request_prefixes_overlap,
    resolve_resource_for_target,
)
from .scope import parse_scope
from .signing import (
    assert_signing_config,
    create_signing_provider,
    sign_with_provider,
    validated_jwks,
)
from .skills import PublishedSkill, SkillCatalog, SkillMeta, load_skill_catalog, parse_skill_catalog
from .types import (
    JWK,
    AuthContext,
    DirectSigningKey,
    DpopKeyPair,
    DynamicSkillProvider,
    DynamicSkillProviderObject,
    IdJagClaims,
    JWTPayload,
    MachineAuthContext,
    MachinePrincipal,
    ProviderSigningKey,
    ReplayStore,
    ScopePolicy,
    Signing,
    SigningKeyProvider,
    SkillProvider,
    SkillVisibility,
    StaticSkillProvider,
    StaticSkillProviderObject,
    UserAuthContext,
    UserPrincipal,
    VerifiedDpop,
    VerifyFailure,
    VerifyResult,
    VerifySuccess,
    WeldallOptions,
)

try:
    __version__ = version("weldall-sdk")
except PackageNotFoundError:  # pragma: no cover - source tree without installation metadata
    __version__ = "0.1.0"

__all__ = [
    "DPOP_FUTURE_SKEW_SECONDS",
    "DPOP_MAX_AGE_SECONDS",
    "ID_JAG_DRAFT",
    "ID_JAG_TOKEN_TYPE",
    "JWK",
    "JWT_DPOP_DRAFT",
    "JWT_DPOP_GRANT",
    "MACHINE_TOKEN_LIFETIME_SECONDS",
    "MACHINE_TOKEN_TYP",
    "PRIVATE_KEY_JWT_ASSERTION_TYPE",
    "REFRESH_TOKEN_TYPE",
    "SKILL_ASSERTION_TYPE",
    "SKILL_CATALOG_PATH",
    "SKILL_CATALOG_SCHEMA_VERSION",
    "SKILL_TAG_LENGTH_LIMIT",
    "SKILL_TAG_LIMIT",
    "TOKEN_EXCHANGE_GRANT",
    "AuthContext",
    "CreateDpopProofInput",
    "DirectSigningKey",
    "DpopKeyPair",
    "DynamicSkillProvider",
    "DynamicSkillProviderObject",
    "ErrorResponse",
    "Headers",
    "IdJagClaims",
    "InMemoryReplayStore",
    "IssueAccessTokenInput",
    "IssueIdJagInput",
    "JWTPayload",
    "JwtSigningInput",
    "JwtVerificationInput",
    "MachineAuthContext",
    "MachineClientAssertionInput",
    "MachineKey",
    "MachinePrincipal",
    "MachineToken",
    "MachineTokenRequestInput",
    "ProviderSigningKey",
    "PublishedSkill",
    "ReplayStore",
    "Request",
    "Response",
    "ScopePolicy",
    "Signing",
    "SigningKeyProvider",
    "SkillCatalog",
    "SkillMeta",
    "SkillProvider",
    "SkillVisibility",
    "StaticSkillProvider",
    "StaticSkillProviderObject",
    "UserAuthContext",
    "UserPrincipal",
    "VerifiedDpop",
    "VerifyAccessTokenInput",
    "VerifyFailure",
    "VerifyIdJagInput",
    "VerifyResult",
    "VerifyStrictDpopInput",
    "VerifySuccess",
    "Weldall",
    "WeldallAuthError",
    "WeldallDiscovery",
    "WeldallHandlers",
    "WeldallOptions",
    "__version__",
    "assert_public_p256",
    "assert_signing_config",
    "base64url_sha256",
    "calculate_jwk_thumbprint",
    "consume_replay",
    "create_dpop_proof",
    "create_machine_client_assertion",
    "create_signing_provider",
    "decode_jwt",
    "decode_protected_header",
    "generate_es256_key_pair",
    "has_verified_email",
    "in_memory",
    "init_weldall",
    "is_sha256_jwk_thumbprint",
    "issue_access_token",
    "issue_id_jag",
    "load_es256_key_pair_from_env",
    "load_skill_catalog",
    "normalize_authorization_server",
    "normalize_htu",
    "normalize_request_prefix",
    "normalize_request_target",
    "normalize_resource_identifier",
    "oauth_error_parts",
    "oauth_error_response",
    "parse_jwk_env",
    "parse_scope",
    "parse_skill_catalog",
    "public_jwk",
    "request_machine_token",
    "request_prefix_accepts",
    "request_prefixes_overlap",
    "resolve_resource_for_target",
    "safe_equal",
    "sign_es256",
    "sign_with_provider",
    "validate_es256_key_pair",
    "validated_jwks",
    "verify_access_token",
    "verify_es256",
    "verify_id_jag",
    "verify_strict_dpop",
]
