// Synchronized mirror of the server's reviewed Atlassian scope catalog. The CLI is
// published independently and must not import application source; parity tests compare both copies.
const defineScopeIds = (value: string) => {
  const ids = value.trim().split(/\s+/);
  if (new Set(ids).size !== ids.length) throw new Error("Duplicate Atlassian OAuth scope ID");
  return ids;
};

/**
 * Reviewed Jira Platform granular scopes.
 * Source: https://developer.atlassian.com/platform/forge/manifest-reference/scopes-product-jira/
 */
export const JIRA_PLATFORM_GRANULAR_SCOPE_IDS = defineScopeIds(`
delete:async-task:jira
delete:attachment:jira
delete:avatar:jira
delete:comment.property:jira
delete:comment:jira
delete:dashboard.property:jira
delete:dashboard:jira
delete:field-configuration-scheme:jira
delete:field-configuration:jira
delete:field.option:jira
delete:field:jira
delete:filter.column:jira
delete:filter:jira
delete:group:jira
delete:issue-link-type:jira
delete:issue-link:jira
delete:issue-type-scheme:jira
delete:issue-type-screen-scheme:jira
delete:issue-type.property:jira
delete:issue-type:jira
delete:issue-worklog.property:jira
delete:issue-worklog:jira
delete:issue.property:jira
delete:issue.remote-link:jira
delete:issue:jira
delete:permission-scheme:jira
delete:permission:jira
delete:project-category:jira
delete:project-role:jira
delete:project-version:jira
delete:project.avatar:jira
delete:project.component:jira
delete:project.property:jira
delete:project:jira
delete:screen-scheme:jira
delete:screen-tab:jira
delete:screen:jira
delete:screenable-field:jira
delete:user-configuration:jira
delete:user.property:jira
delete:webhook:jira
delete:workflow-scheme:jira
delete:workflow.property:jira
delete:workflow:jira
read:application-role:jira
read:attachment:jira
read:audit-log:jira
read:avatar:jira
read:comment.property:jira
read:comment:jira
read:custom-field-contextual-configuration:jira
read:dashboard.property:jira
read:dashboard:jira
read:email-address:jira
read:field-configuration-scheme:jira
read:field-configuration:jira
read:field.default-value:jira
read:field.option:jira
read:field.options:jira
read:field:jira
read:filter.column:jira
read:filter.default-share-scope:jira
read:filter:jira
read:group:jira
read:instance-configuration:jira
read:issue-details:jira
read:issue-event:jira
read:issue-field-values:jira
read:issue-link-type:jira
read:issue-link:jira
read:issue-meta:jira
read:issue-security-level:jira
read:issue-security-scheme:jira
read:issue-status:jira
read:issue-type-hierarchy:jira
read:issue-type-scheme:jira
read:issue-type-screen-scheme:jira
read:issue-type-transition:jira
read:issue-type.property:jira
read:issue-type:jira
read:issue-worklog.property:jira
read:issue-worklog:jira
read:issue.changelog:jira
read:issue.property:jira
read:issue.remote-link:jira
read:issue.time-tracking:jira
read:issue.transition:jira
read:issue.watcher:jira
read:issue:jira
read:jira-expressions:jira
read:jql:jira
read:label:jira
read:license:jira
read:notification-scheme:jira
read:permission-scheme:jira
read:permission:jira
read:priority:jira
read:project-category:jira
read:project-role:jira
read:project-type:jira
read:project-version:jira
read:project.avatar:jira
read:project.component:jira
read:project.email:jira
read:project.feature:jira
read:project.property:jira
read:project:jira
read:resolution:jira
read:role:jira
read:screen-field:jira
read:screen-scheme:jira
read:screen-tab:jira
read:screen:jira
read:screenable-field:jira
read:status:jira
read:user-configuration:jira
read:user.columns:jira
read:user.property:jira
read:user:jira
read:webhook:jira
read:workflow-scheme:jira
read:workflow.property:jira
read:workflow:jira
send:notification:jira
validate:jql:jira
write:attachment:jira
write:avatar:jira
write:comment.property:jira
write:comment:jira
write:custom-field-contextual-configuration:jira
write:dashboard.property:jira
write:dashboard:jira
write:field-configuration-scheme:jira
write:field-configuration:jira
write:field.default-value:jira
write:field.option:jira
write:field:jira
write:filter.column:jira
write:filter.default-share-scope:jira
write:filter:jira
write:group:jira
write:instance-configuration:jira
write:issue-link-type:jira
write:issue-link:jira
write:issue-type-scheme:jira
write:issue-type-screen-scheme:jira
write:issue-type.property:jira
write:issue-type:jira
write:issue-worklog.property:jira
write:issue-worklog:jira
write:issue.property:jira
write:issue.remote-link:jira
write:issue.time-tracking:jira
write:issue.vote:jira
write:issue.watcher:jira
write:issue:jira
write:permission-scheme:jira
write:permission:jira
write:project-category:jira
write:project-role:jira
write:project-version:jira
write:project.avatar:jira
write:project.component:jira
write:project.email:jira
write:project.feature:jira
write:project.property:jira
write:project:jira
write:screen-scheme:jira
write:screen-tab:jira
write:screen:jira
write:screenable-field:jira
write:user-configuration:jira
write:user.property:jira
write:webhook:jira
write:workflow-scheme:jira
write:workflow.property:jira
write:workflow:jira
`);

/**
 * Jira Software granular scopes for the /rest/agile/1.0 routes accepted by Weldall.
 * Source: https://developer.atlassian.com/cloud/jira/software/scopes-for-oauth-2-3LO-and-forge-apps/
 */
export const JIRA_SOFTWARE_GRANULAR_SCOPE_IDS = defineScopeIds(`
delete:board-scope.admin:jira-software
delete:sprint:jira-software
read:board-scope.admin:jira-software
read:board-scope:jira-software
read:epic:jira-software
read:issue:jira-software
read:sprint:jira-software
write:board-scope.admin:jira-software
write:board-scope:jira-software
write:epic:jira-software
write:issue:jira-software
write:sprint:jira-software
`);

/**
 * Jira Service Management granular scopes for the /rest/servicedeskapi routes accepted by Weldall.
 * Assets/CMDB scopes are excluded because their separate gateway routes are not accepted.
 * Source: https://developer.atlassian.com/cloud/jira/service-desk/scopes-for-oauth-2-3LO-and-forge-apps/
 */
export const JIRA_SERVICE_MANAGEMENT_GRANULAR_SCOPE_IDS = defineScopeIds(`
delete:customer.detail-field:jira-service-management
delete:entitlement.detail-field:jira-service-management
delete:entitlement:jira-service-management
delete:organization.detail-field:jira-service-management
delete:organization.property:jira-service-management
delete:organization.user:jira-service-management
delete:organization:jira-service-management
delete:product:jira-service-management
delete:request.feedback:jira-service-management
delete:request.notification:jira-service-management
delete:request.participant:jira-service-management
delete:requesttype.property:jira-service-management
delete:servicedesk.customer:jira-service-management
delete:servicedesk.organization:jira-service-management
delete:servicedesk.property:jira-service-management
read:customer.detail-field:jira-service-management
read:customer.detail:jira-service-management
read:customer:jira-service-management
read:entitlement.detail-field:jira-service-management
read:entitlement.detail:jira-service-management
read:entitlement:jira-service-management
read:knowledgebase:jira-service-management
read:organization.detail-field:jira-service-management
read:organization.detail:jira-service-management
read:organization.property:jira-service-management
read:organization.user:jira-service-management
read:organization:jira-service-management
read:product:jira-service-management
read:queue:jira-service-management
read:request.action:jira-service-management
read:request.approval:jira-service-management
read:request.attachment:jira-service-management
read:request.comment:jira-service-management
read:request.feedback:jira-service-management
read:request.notification:jira-service-management
read:request.participant:jira-service-management
read:request.sla:jira-service-management
read:request.status:jira-service-management
read:request:jira-service-management
read:requesttype.property:jira-service-management
read:requesttype:jira-service-management
read:servicedesk.customer:jira-service-management
read:servicedesk.organization:jira-service-management
read:servicedesk.property:jira-service-management
read:servicedesk:jira-service-management
write:customer.detail-field:jira-service-management
write:customer.detail:jira-service-management
write:customer:jira-service-management
write:entitlement.detail-field:jira-service-management
write:entitlement.detail:jira-service-management
write:organization.detail-field:jira-service-management
write:organization.detail:jira-service-management
write:organization.property:jira-service-management
write:organization.user:jira-service-management
write:organization:jira-service-management
write:product:jira-service-management
write:request.approval:jira-service-management
write:request.attachment:jira-service-management
write:request.comment:jira-service-management
write:request.feedback:jira-service-management
write:request.notification:jira-service-management
write:request.participant:jira-service-management
write:request.status:jira-service-management
write:request:jira-service-management
write:requesttype.property:jira-service-management
write:requesttype:jira-service-management
write:servicedesk.customer:jira-service-management
write:servicedesk.organization:jira-service-management
write:servicedesk.property:jira-service-management
`);

/**
 * Reviewed Confluence granular scopes for the v1/v2 routes accepted by Weldall.
 * Source: https://developer.atlassian.com/cloud/confluence/scopes-for-oauth-2-3LO-and-forge-apps/
 */
export const CONFLUENCE_GRANULAR_SCOPE_IDS = defineScopeIds(`
delete:attachment:confluence
delete:blogpost:confluence
delete:comment:confluence
delete:content:confluence
delete:custom-content:confluence
delete:database:confluence
delete:embed:confluence
delete:folder:confluence
delete:page:confluence
delete:space:confluence
delete:whiteboard:confluence
read:analytics.content:confluence
read:attachment:confluence
read:audit-log:confluence
read:blogpost:confluence
read:comment:confluence
read:configuration:confluence
read:content-details:confluence
read:content.metadata:confluence
read:content.permission:confluence
read:content.property:confluence
read:content.restriction:confluence
read:content:confluence
read:custom-content:confluence
read:database:confluence
read:email-address:confluence
read:embed:confluence
read:folder:confluence
read:group:confluence
read:hierarchical-content:confluence
read:inlinetask:confluence
read:label:confluence
read:page:confluence
read:relation:confluence
read:space-details:confluence
read:space.permission:confluence
read:space.property:confluence
read:space.setting:confluence
read:space:confluence
read:task:confluence
read:template:confluence
read:user.property:confluence
read:user:confluence
read:watcher:confluence
read:whiteboard:confluence
write:attachment:confluence
write:audit-log:confluence
write:blogpost:confluence
write:comment:confluence
write:configuration:confluence
write:content.property:confluence
write:content.restriction:confluence
write:content:confluence
write:custom-content:confluence
write:database:confluence
write:embed:confluence
write:folder:confluence
write:group:confluence
write:inlinetask:confluence
write:label:confluence
write:page:confluence
write:relation:confluence
write:space.permission:confluence
write:space.property:confluence
write:space.setting:confluence
write:space:confluence
write:task:confluence
write:template:confluence
write:user.property:confluence
write:watcher:confluence
write:whiteboard:confluence
`);

export const JIRA_GRANULAR_SCOPE_IDS = [
  ...new Set([
    ...JIRA_PLATFORM_GRANULAR_SCOPE_IDS,
    ...JIRA_SOFTWARE_GRANULAR_SCOPE_IDS,
    ...JIRA_SERVICE_MANAGEMENT_GRANULAR_SCOPE_IDS,
  ]),
].sort();
